import type { LPMComponents, LPMSessionMethodName } from "../types";

export type SessionFieldType = "phone" | "billingAddress" | "taxInfo" | "expiryDate" | "dateOfBirth" | "numberOfInstallments" | "bic" | "identification";

export interface LPMConfig {
  readonly component: LPMComponents;
  readonly buttonTag: string;
  readonly sessionMethod: LPMSessionMethodName;
  readonly displayName: string;
  readonly fields: readonly string[];
  readonly sessionFields: readonly SessionFieldType[];
  readonly testBuyerCountry: string;
}

export const LPM_REGISTRY = {
  ideal: {
    component: "ideal-payments",
    buttonTag: "ideal-button",
    sessionMethod: "createIdealOneTimePaymentSession",
    displayName: "iDEAL",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "NL",
  },
  bancontact: {
    component: "bancontact-payments",
    buttonTag: "bancontact-button",
    sessionMethod: "createBancontactOneTimePaymentSession",
    displayName: "Bancontact",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "BE",
  },
  eps: {
    component: "eps-payments",
    buttonTag: "eps-button",
    sessionMethod: "createEpsOneTimePaymentSession",
    displayName: "EPS",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AT",
  },
  blik: {
    component: "blik-payments",
    buttonTag: "blik-button",
    sessionMethod: "createBlikOneTimePaymentSession",
    displayName: "BLIK",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  mybank: {
    component: "mybank-payments",
    buttonTag: "mybank-button",
    sessionMethod: "createMyBankOneTimePaymentSession",
    displayName: "MyBank",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
  },
  trustly: {
    component: "trustly-payments",
    buttonTag: "trustly-button",
    sessionMethod: "createTrustlyOneTimePaymentSession",
    displayName: "Trustly",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "SE",
  },
  p24: {
    component: "p24-payments",
    buttonTag: "p24-button",
    sessionMethod: "createP24OneTimePaymentSession",
    displayName: "Przelewy24",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  multibanco: {
    component: "multibanco-payments",
    buttonTag: "multibanco-button",
    sessionMethod: "createMultibancoOneTimePaymentSession",
    displayName: "Multibanco",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PT",
  },
  bizum: {
    component: "bizum-payments",
    buttonTag: "bizum-button",
    sessionMethod: "createBizumOneTimePaymentSession",
    displayName: "Bizum",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "ES",
  },
  swish: {
    component: "swish-payments",
    buttonTag: "swish-button",
    sessionMethod: "createSwishOneTimePaymentSession",
    displayName: "Swish",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SE",
  },
  twint: {
    component: "twint-payments",
    buttonTag: "twint-button",
    sessionMethod: "createTwintOneTimePaymentSession",
    displayName: "TWINT",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CH",
  },
  wechatpay: {
    component: "wechatpay-payments",
    buttonTag: "wechatpay-button",
    sessionMethod: "createWechatpayOneTimePaymentSession",
    displayName: "WeChat Pay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
  },
  verkkopankki: {
    component: "verkkopankki-payments",
    buttonTag: "verkkopankki-button",
    sessionMethod: "createVerkkopankkiOneTimePaymentSession",
    displayName: "Verkkopankki",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "FI",
  },
  payu: {
    component: "payu-payments",
    buttonTag: "payu-button",
    sessionMethod: "createPayuOneTimePaymentSession",
    displayName: "PayU",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  mbway: {
    component: "mbway-payments",
    buttonTag: "mbway-button",
    sessionMethod: "createMbWayOneTimePaymentSession",
    displayName: "MB WAY",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "PT",
  },
  satispay: {
    component: "satispay-payments",
    buttonTag: "satispay-button",
    sessionMethod: "createSatispayOneTimePaymentSession",
    displayName: "Satispay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
  },
  wero: {
    component: "wero-payments",
    buttonTag: "wero-button",
    sessionMethod: "createWeroOneTimePaymentSession",
    displayName: "Wero",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  floa: {
    component: "floa-payments",
    buttonTag: "floa-button",
    sessionMethod: "createFloaOneTimePaymentSession",
    displayName: "FLOA",
    fields: ["name"],
    sessionFields: ["dateOfBirth", "numberOfInstallments"],
    testBuyerCountry: "FR",
  },
  grabpay: {
    component: "grabpay-payments",
    buttonTag: "grabpay-button",
    sessionMethod: "createGrabpayOneTimePaymentSession",
    displayName: "GrabPay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SG",
  },
  pixInternational: {
    component: "pix-international-payments",
    buttonTag: "pix-international-button",
    sessionMethod: "createPixInternationalOneTimePaymentSession",
    displayName: "Pix",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress", "taxInfo"],
    testBuyerCountry: "BR",
  },
  sepa: {
    component: "sepa-payments",
    buttonTag: "sepa-button",
    sessionMethod: "createSepaOneTimePaymentSession",
    displayName: "SEPA",
    fields: [],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  doku: {
    component: "doku-payments",
    buttonTag: "doku-button",
    sessionMethod: "createDOKUOneTimePaymentSession",
    displayName: "DOKU",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  estonia: {
    component: "estoniabank-payments",
    buttonTag: "estoniabank-button",
    sessionMethod: "createEstoniaOneTimePaymentSession",
    displayName: "Estonia Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "EE",
  },
  gopay: {
    component: "gopay-payments",
    buttonTag: "gopay-button",
    sessionMethod: "createGopayOneTimePaymentSession",
    displayName: "GoPay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  alipay: {
    component: "alipay-payments",
    buttonTag: "alipay-button",
    sessionMethod: "createAlipayOneTimePaymentSession",
    displayName: "Alipay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
  },
  indonesiaBanks: {
    component: "indonesiabanks-payments",
    buttonTag: "indonesiabanks-button",
    sessionMethod: "createIndonesiaBanksOneTimePaymentSession",
    displayName: "Indonesia Banks",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  kredivo: {
    component: "kredivo-payments",
    buttonTag: "kredivo-button",
    sessionMethod: "createKredivoOneTimePaymentSession",
    displayName: "Kredivo",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "ID",
  },
  linkaja: {
    component: "linkaja-payments",
    buttonTag: "linkaja-button",
    sessionMethod: "createLinkajaOneTimePaymentSession",
    displayName: "LinkAja",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  ovo: {
    component: "ovo-payments",
    buttonTag: "ovo-button",
    sessionMethod: "createOvoOneTimePaymentSession",
    displayName: "OVO",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  paysera: {
    component: "paysera-payments",
    buttonTag: "paysera-button",
    sessionMethod: "createPayseraOneTimePaymentSession",
    displayName: "Paysera",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "LT",
  },
  skrill: {
    component: "skrill-payments",
    buttonTag: "skrill-button",
    sessionMethod: "createSkrillOneTimePaymentSession",
    displayName: "Skrill",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  blikPayLater: {
    component: "blikpaylater-payments",
    buttonTag: "blikpaylater-button",
    sessionMethod: "createBlikPayLaterOneTimePaymentSession",
    displayName: "BLIK Pay Later",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  bancomatPay: {
    component: "bancomatpay-payments",
    buttonTag: "bancomatpay-button",
    sessionMethod: "createBancomatPayOneTimePaymentSession",
    displayName: "Bancomat Pay",
    fields: ["name"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "IT",
  },
  jeniuspay: {
    component: "jeniuspay-payments",
    buttonTag: "jeniuspay-button",
    sessionMethod: "createJeniuspayOneTimePaymentSession",
    displayName: "Jeniuspay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  klarna: {
    component: "klarna-payments",
    buttonTag: "klarna-button",
    sessionMethod: "createKlarnaOneTimePaymentSession",
    displayName: "Klarna",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "SE",
  },
  afterpay: {
    component: "afterpay-payments",
    buttonTag: "afterpay-button",
    sessionMethod: "createAfterpayOneTimePaymentSession",
    displayName: "Afterpay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "AU",
  },
  oxxopay: {
    component: "oxxopay-payments",
    buttonTag: "oxxopay-button",
    sessionMethod: "createOxxopayOneTimePaymentSession",
    displayName: "OXXO",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "MX",
  },
  boletobancario: {
    component: "boletobancario-payments",
    buttonTag: "boletobancario-button",
    sessionMethod: "createBoletobancarioOneTimePaymentSession",
    displayName: "Boleto Bancário",
    fields: ["name", "email"],
    sessionFields: ["taxInfo"],
    testBuyerCountry: "BR",
  },
  paysafecard: {
    component: "paysafecard-payments",
    buttonTag: "paysafecard-button",
    sessionMethod: "createPaysafecardOneTimePaymentSession",
    displayName: "Paysafecard",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AT",
  },
  scalapay: {
    component: "scalapay-payments",
    buttonTag: "scalapay-button",
    sessionMethod: "createScalapayOneTimePaymentSession",
    displayName: "Scalapay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "IT",
  },
  crypto: {
    component: "crypto-payments",
    buttonTag: "crypto-button",
    sessionMethod: "createCryptoOneTimePaymentSession",
    displayName: "Crypto",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "US",
  },
  dragonpay: {
    component: "dragonpay-payments",
    buttonTag: "dragonpay-button",
    sessionMethod: "createDragonpayOneTimePaymentSession",
    displayName: "Dragonpay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PH",
  },
  fpx: {
    component: "fpx-payments",
    buttonTag: "fpx-button",
    sessionMethod: "createFpxOneTimePaymentSession",
    displayName: "FPX",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "MY",
  },
  indomaret: {
    component: "indomaret-payments",
    buttonTag: "indomaret-button",
    sessionMethod: "createIndomaretOneTimePaymentSession",
    displayName: "Indomaret",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "ID",
  },
  thailandBanks: {
    component: "thailandbanks-payments",
    buttonTag: "thailandbanks-button",
    sessionMethod: "createThailandBanksOneTimePaymentSession",
    displayName: "Thailand Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "TH",
  },
  alfamart: {
    component: "alfamart-payments",
    buttonTag: "alfamart-button",
    sessionMethod: "createAlfamartOneTimePaymentSession",
    displayName: "Alfamart",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "ID",
  },
  zip: {
    component: "zip-payments",
    buttonTag: "zip-button",
    sessionMethod: "createZipOneTimePaymentSession",
    displayName: "Zip",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AU",
  },
  latviaBanks: {
    component: "latviabanks-payments",
    buttonTag: "latviabanks-button",
    sessionMethod: "createLatviaBanksOneTimePaymentSession",
    displayName: "Latvia Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "LV",
  },
  fiuu: {
    // FIUU's SDK component is "fiuu-cash-payments" but the registered
    // custom-element button tag is "fiuu-button" (not "fiuu-cash-button"),
    // so buttonTag does NOT follow the standard component→tag derivation.
    component: "fiuu-cash-payments",
    buttonTag: "fiuu-button",
    sessionMethod: "createFIUUOneTimePaymentSession",
    displayName: "FIUU",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "MY",
  },
  lithuaniaBanks: {
    component: "lithuaniabanks-payments",
    buttonTag: "lithuaniabanks-button",
    sessionMethod: "createLithuaniaBanksOneTimePaymentSession",
    displayName: "Lithuania Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "LT",
  },
  airtelKenya: {
    component: "airtelkenya-payments",
    buttonTag: "airtelkenya-button",
    sessionMethod: "createAirtelKenyaOneTimePaymentSession",
    displayName: "Airtel Kenya",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "KE",
  },
  airtelTanzania: {
    component: "airtel-tanzania-payments",
    buttonTag: "airtel-tanzania-button",
    sessionMethod: "createAirtelTanzaniaOneTimePaymentSession",
    displayName: "Airtel Tanzania",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "TZ",
  },
  pesalink: {
    component: "pesalink-payments",
    buttonTag: "pesalink-button",
    sessionMethod: "createPesalinkOneTimePaymentSession",
    displayName: "PesaLink",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "KE",
  },
  halopesa: {
    component: "halopesa-payments",
    buttonTag: "halopesa-button",
    sessionMethod: "createHalopesaOneTimePaymentSession",
    displayName: "HaloPesa",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "TZ",
  },
  spei: {
    component: "spei-payments",
    buttonTag: "spei-button",
    sessionMethod: "createSpeiOneTimePaymentSession",
    displayName: "SPEI",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "MX",
  },
  picpay: {
    component: "picpay-payments",
    buttonTag: "picpay-button",
    sessionMethod: "createPicpayOneTimePaymentSession",
    displayName: "PicPay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "BR",
  },
  nigeriaBanks: {
    component: "nigeria-banks-payments",
    buttonTag: "nigeria-banks-button",
    sessionMethod: "createNigeriaBanksOneTimePaymentSession",
    displayName: "Nigeria Banks",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "NG",
  },
  opay: {
    component: "opay-payments",
    buttonTag: "opay-button",
    sessionMethod: "createOpayOneTimePaymentSession",
    displayName: "OPay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "NG",
  },
  naverpay: {
    component: "naverpay-payments",
    buttonTag: "naverpay-button",
    sessionMethod: "createNaverpayOneTimePaymentSession",
    displayName: "Naver Pay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "KR",
  },
  codi: {
    component: "codi-payments",
    buttonTag: "codi-button",
    sessionMethod: "createCodiOneTimePaymentSession",
    displayName: "CoDi",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "MX",
  },
  payattitude: {
    component: "payattitude-payments",
    buttonTag: "payattitude-button",
    sessionMethod: "createPayattitudeOneTimePaymentSession",
    displayName: "Payattitude",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "NG",
  },
  dimo: {
    component: "dimo-payments",
    buttonTag: "dimo-button",
    sessionMethod: "createDimoOneTimePaymentSession",
    displayName: "Dimo",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "BR",
  },
  pse: {
    component: "pse-payments",
    buttonTag: "pse-button",
    sessionMethod: "createPseOneTimePaymentSession",
    displayName: "PSE",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress", "bic", "identification"],
    testBuyerCountry: "CO",
  },
  qrph: {
    component: "qrph-payments",
    buttonTag: "qrph-button",
    sessionMethod: "createQrphOneTimePaymentSession",
    displayName: "QRPh",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PH",
  },
  vietqr: {
    component: "vietqr-payments",
    buttonTag: "vietqr-button",
    sessionMethod: "createVietqrOneTimePaymentSession",
    displayName: "VietQR",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "VN",
  },
  mixxByYas: {
    component: "mixx-by-yas-payments",
    buttonTag: "mixx-by-yas-button",
    sessionMethod: "createMixxByYasOneTimePaymentSession",
    displayName: "Mixx by Yas",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "TG",
  },
  breB: {
    component: "bre-b-payments",
    buttonTag: "bre-b-button",
    sessionMethod: "createBreBOneTimePaymentSession",
    displayName: "Bre-B",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "CO",
  },
  promptpayQr: {
    component: "promptpay-qr-payments",
    buttonTag: "promptpay-qr-button",
    sessionMethod: "createPromptpayQrOneTimePaymentSession",
    displayName: "PromptPay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "TH",
  },
  nequi: {
    component: "nequi-payments",
    buttonTag: "nequi-button",
    sessionMethod: "createNequiOneTimePaymentSession",
    displayName: "Nequi",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress", "identification"],
    testBuyerCountry: "CO",
  },
  truemoney: {
    component: "truemoney-payments",
    buttonTag: "truemoney-button",
    sessionMethod: "createTruemoneyOneTimePaymentSession",
    displayName: "TrueMoney",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "TH",
  },
  nupay: {
    component: "nupay-payments",
    buttonTag: "nupay-button",
    sessionMethod: "createNupayOneTimePaymentSession",
    displayName: "NuPay",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "IN",
  },
  shopeepay: {
    component: "shopeepay-payments",
    buttonTag: "shopeepay-button",
    sessionMethod: "createShopeepayOneTimePaymentSession",
    displayName: "ShopeePay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
} as const satisfies Record<string, LPMConfig>;

export type LPMName = keyof typeof LPM_REGISTRY;
